version: 3

tasks:
  default:
    cmds:
      - task: test

  test:
    cmds:
      - odin test . -out:bin/test -o:none -debug
    sources:
      - ./**/*.odin
    aliases:
      - t
    method: none
    silent: true

  clean:
    cmds:
      - rm -rf ./cli
    aliases:
      - c
    silent: true

interval: 250ms
